# MySQL - Prod
spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/vidya_sampadana_db?serverTimezone=UTC&useSSL=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Prod
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# MongoDB - Prod (uncomment if needed)
# spring.data.mongodb.uri=${MONGO_URI}