# MySQL - Dev
spring.datasource.url=jdbc:mysql://localhost:3306/vidya_sampadana_db?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Anni@2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA - Dev
<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
=======
spring.jpa.hibernate.ddl-auto=validate
>>>>>>> sub_me/main
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# MongoDB - Dev (uncomment if needed)
# spring.data.mongodb.uri=mongodb://localhost:27017/student_logs_db