spring.application.name=chat-service
server.port=8085

spring.mongodb.uri=mongodb+srv://chat_db_user_1:chat1234@cluster0.ypardi7.mongodb.net/?appName=Cluster0
spring.mongodb.database=vidya-chat

eureka.client.enabled=false
