server:
  port: 8092 # Student=8081, Mentor=8082, Session=8083, Payment=8084, IAM=8085, User=8086, Document=8087, Notification=8088, Course=8089, Analytics=8090, Chat=8092

spring:
  application:
    name: chat-service

  

