server:
  port: 8091 # Next available port

spring:
  application:
    name: activity-logging-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/activity_logs_db

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
